# Example configuration for multiple mailboxes
# Copy this to config.yaml and modify with your settings

servers:
  # First Gmail account (Personal)
  - name: "personal-gmail"
    pop3:
      host: "pop.gmail.com"
      port: 995
      use_tls: true
      username: "personal@gmail.com"
      password: "your-gmail-app-password-1"
    imap:
      host: "imap.gmail.com"
      port: 993
      use_tls: true
      username: "personal@gmail.com"
      password: "your-gmail-app-password-1"
    smtp:
      host: "smtp.gmail.com"
      port: 587
      use_tls: true
      username: "personal@gmail.com"
      password: "your-gmail-app-password-1"

  # Second Gmail account (Work)
  - name: "work-gmail"
    pop3:
      host: "pop.gmail.com"
      port: 995
      use_tls: true
      username: "work@gmail.com"
      password: "your-gmail-app-password-2"
    imap:
      host: "imap.gmail.com"
      port: 993
      use_tls: true
      username: "work@gmail.com"
      password: "your-gmail-app-password-2"
    smtp:
      host: "smtp.gmail.com"
      port: 587
      use_tls: true
      username: "work@gmail.com"
      password: "your-gmail-app-password-2"

  # Outlook/Hotmail account
  - name: "business-outlook"
    pop3:
      host: "outlook.office365.com"
      port: 995
      use_tls: true
      username: "business@company.com"
      password: "your-outlook-password"
    imap:
      host: "outlook.office365.com"
      port: 993
      use_tls: true
      username: "business@company.com"
      password: "your-outlook-password"
    smtp:
      host: "smtp-mail.outlook.com"
      port: 587
      use_tls: true
      username: "business@company.com"
      password: "your-outlook-password"

  # Yandex account
  - name: "yandex-account"
    pop3:
      host: "pop.yandex.com"
      port: 995
      use_tls: true
      username: "username@yandex.com"
      password: "your-yandex-password"
    imap:
      host: "imap.yandex.com"
      port: 993
      use_tls: true
      username: "username@yandex.com"
      password: "your-yandex-password"
    smtp:
      host: "smtp.yandex.com"
      port: 587
      use_tls: true
      username: "username@yandex.com"
      password: "your-yandex-password"

# Local server settings (what your legacy email client connects to)
# Both POP3 and SMTP are supported for local connections - this is for legacy clients
local:
  pop3:
    host: "0.0.0.0"  # Listen on all interfaces
    port: 110         # Standard POP3 port
    use_tls: false    # No encryption for local connections
  smtp:
    host: "0.0.0.0"  # Listen on all interfaces
    port: 25          # Standard SMTP port (or use 587, 2525 for alternatives)
    use_tls: false    # No encryption for local connections

# Notes:
# 1. For Gmail, you must use App Passwords (not your regular password)
# 2. Enable 2-Factor Authentication in Gmail first
# 3. Generate App Password: Google Account → Security → 2-Step Verification → App passwords
# 4. The proxy will automatically handle authentication with upstream servers
# 5. Configure your legacy email client to use POP3 only:
#    - Server: localhost, Port: 110, Security: None
# 6. Use any username/password in your email client - they will be ignored
# 7. The proxy can connect to upstream servers using either POP3 or IMAP
# 8. If both POP3 and IMAP are configured, POP3 takes preference
# 9. If only IMAP is configured, the proxy will translate POP3 <-> IMAP

